### ISSUE TITLE
Team members need to be change the visibility in the organization

### ISSUE THREAD

**Issue by Neustradamus** [xaraya-modules/twig#1]
Dear @xaraya, @xaraya-modules teams, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

Can you change the "Private" to "Public" visibility in the organization?
- https://github.com/orgs/xaraya-modules/people

It will be same for main place when the specified ticket will be solved:
- https://github.com/xaraya

I have done two tickets here:
- https://github.com/xaraya/core/issues/59
- https://github.com/xaraya/core/issues/60

Thanks in advance.

**Comment by mikespub** [comment]
@Neustradamus seems to have some automated action submitting random issues to multiple repositories
This issue is irrelevant

**Comment by Neustradamus** [comment]
@mikespub: I am not a bot, please reopen this ticket, the problem is not solved.
Thanks in advance.
