### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [xaraya-modules/twig#2]
Dear @xaraya, @xaraya-modules teams, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example:
- https://sourceforge.net/p/xarayamodules/

Please replace the website by the GitHub (https://github.com/xarayamodules):
- https://sourceforge.net/projects/xarayamodules/
- https://sourceforge.net/projects/xarayamodules/support

Keep only the GitHub (https://github.com/xarayamodules):
- https://sourceforge.net/p/xarayamodules/_list/link

To disable/delete tabs, go here: https://sourceforge.net/projects/xarayamodules/
To add a new tab, go here: https://sourceforge.net/projects/xarayamodules/
To change informations, go here: https://sourceforge.net/p/xarayamodules/admin/overview
To export, go here: https://sourceforge.net/p/xarayamodules/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/xarayamodules/admin/overview
- A new tab, go here: https://sourceforge.net/projects/xarayamodules/

Thanks in advance.

Linked to:
- https://github.com/xaraya/core/issues/60
- https://github.com/xaraya/core/issues/59
- https://github.com/xaraya-modules/twig/issues/1

**Comment by mikespub** [comment]
@Neustradamus seems to have some automated action submitting random issues to multiple repositories
This issue is irrelevant

**Comment by Neustradamus** [comment]
@mikespub: I am not a bot, please reopen this ticket, the problem is not solved.
Thanks in advance.
