### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [xaraya-modules/twig#3]
Dear @xaraya, @xaraya-modules teams, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example:
- https://sourceforge.net/p/xarayamodules/

Please replace the website by the GitHub (https://github.com/xarayamodules):
- https://sourceforge.net/projects/xarayamodules/
- https://sourceforge.net/projects/xarayamodules/support

Keep only the GitHub (https://github.com/xarayamodules):
- https://sourceforge.net/p/xarayamodules/_list/link

To disable/delete tabs, go here: https://sourceforge.net/projects/xarayamodules/
To add a new tab, go here: https://sourceforge.net/projects/xarayamodules/
To change informations, go here: https://sourceforge.net/p/xarayamodules/admin/overview
To export, go here: https://sourceforge.net/p/xarayamodules/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/xarayamodules/admin/overview
- A new tab, go here: https://sourceforge.net/projects/xarayamodules/

Thanks in advance.

There was a previous ticket but one guy has closed it without solution:
- https://github.com/xaraya-modules/twig/issues/2

Linked to:
- https://github.com/xaraya/core/issues/59
- https://github.com/xaraya/core/issues/60
- https://github.com/xaraya/core/issues/61
- https://github.com/xaraya/core/issues/62
- https://github.com/xaraya-modules/twig/issues/1
- https://github.com/xaraya-modules/twig/issues/2
- https://github.com/xaraya-modules/twig/issues/3
- https://github.com/xaraya-modules/twig/issues/4

**Comment by mikespub** [comment]
Dear @Neustradamus this repository has never been hosted on Sourceforge and I have absolutely no plans to ever copy them there.

**Comment by Neustradamus** [comment]
@mikespub: Please do not close an unsolved ticket, please reopen.

You can see here the team on Sourceforge:
- https://sourceforge.net/p/xarayamodules/_members/

Thanks in advance.

**Comment by Neustradamus** [comment]
@mikespub: Please do not close an unsolved ticket, please reopen.

You can see here the team on Sourceforge:
- Xaraya: https://sourceforge.net/p/xaraya/_members/
- Modules: https://sourceforge.net/p/xarayamodules/_members/
- Themes: https://sourceforge.net/p/xarayathemes/_members/

Thanks in advance.

**Comment by mikespub** [comment]
Hi @Neustradamus

Let me try to explain once again - Sourceforge is not and has never been the master of the Xaraya source code, it's only an outdated copy & file distribution from more than 10 years ago.

So there is absolutely no reason to migrate that old stuff, unless you want to keep it for personal reasons - in which case, feel free to fork it yourself.
