### ISSUE TITLE
Team members need to be change the visibility in the organization

### ISSUE THREAD

**Issue by Neustradamus** [xaraya-modules/twig#4]
Dear @xaraya, @xaraya-modules teams, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

Can you change the "Private" to "Public" visibility in the organization?
- https://github.com/orgs/xaraya-modules/people

It will be same for main place when the specified ticket will be solved:
- https://github.com/xaraya

I have done two tickets here:
- https://github.com/xaraya/core/issues/59
- https://github.com/xaraya/core/issues/60

There was a previous ticket but one guy has closed it without solution:
- https://github.com/xaraya-modules/twig/issues/1

Thanks in advance.

**Comment by mikespub** [comment]
See #3

**Comment by Neustradamus** [comment]
@mikespub: Please do not close an unsolved ticket, please reopen.

Thanks in advance.
